language: rust
rust:
  - 1.46.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: 1.46.0  # dependencies lack MSRV policies, so cannot pin
    - rust: beta
    - rust: nightly
script:
  - cargo build --all-targets --verbose
  - cargo test --verbose
  - cargo test --verbose --no-default-features
  - cargo test --verbose --all-features
